apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-platform.fullname" . }}-secrets
  labels:
    {{- include "secure-api-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.password }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc }}