apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secure-api-platform.fullname" . }}-config
  labels:
    {{- include "secure-api-platform.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.monitoring.prometheus.evaluationInterval }}
    scrape_configs:
      - job_name: 'secure-api-platform'
        static_configs:
          - targets: ['{{ include "secure-api-platform.fullname" . }}-app:{{ .Values.service.app.port }}']
        metrics_path: '/metrics'