apiVersion: v2
name: secure-api-platform
description: A Helm chart for the Secure API Management Platform
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: "Femi Akinlotan"
    email: "femi.akinlotan@devopsfoundry.com"
