# Default values for secure-api-platform
replicaCount:
  app: 1
  postgres: 1
  prometheus: 1
  grafana: 1
  jaeger: 1
  swaggerui: 1

image:
  app:
    repository: crypticseeds/secure-api-management-platform
    tag: latest
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  swaggerui:
    repository: swaggerapi/swagger-ui
    tag: latest
    pullPolicy: IfNotPresent
  prometheus:
    repository: prom/prometheus
    tag: latest
    pullPolicy: IfNotPresent
  grafana:
    repository: grafana/grafana
    tag: latest
    pullPolicy: IfNotPresent
  jaeger:
    repository: jaegertracing/all-in-one
    tag: latest
    pullPolicy: IfNotPresent

service:
  app:
    type: ClusterIP
    port: 8080
  postgres:
    port: 5432
  prometheus:
    port: 9090
  grafana:
    port: 3000
  jaeger:
    ports:
      ui: 16686
      collector: 14250
  swaggerui:
    type: ClusterIP
    port: 8081

ingress:
  enabled: true
  className: nginx
  host: secure-api-platform.local
  tls: false

postgresql:
  database: apisecurity
  username: postgres
  password: postgres123
  persistence:
    enabled: true
    size: 1Gi
    prometheus:
      enabled: true
      size: 1Gi
    grafana:
      enabled: true
      size: 1Gi

resources:
  app:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  postgres:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

monitoring:
  prometheus:
    scrapeInterval: 15s
    evaluationInterval: 15s
