apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secure-api-platform.fullname" . }}-postgres-pvc
  labels:
    {{- include "secure-api-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}