apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-api-platform.fullname" . }}-prometheus
  labels:
    {{- include "secure-api-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/created-by: "Femi.Akinlotan"
spec:
  replicas: {{ .Values.replicaCount.prometheus }}
  selector:
    matchLabels:
      {{- include "secure-api-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "secure-api-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.image.prometheus.repository }}:{{ .Values.image.prometheus.tag }}"
        imagePullPolicy: {{ .Values.image.prometheus.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.prometheus.port }}
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/
      volumes:
      - name: config
        configMap:
          name: {{ include "secure-api-platform.fullname" . }}-config 