apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-api-platform.fullname" . }}-prometheus
  labels:
    {{- include "secure-api-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.prometheus.port }}
      targetPort: {{ .Values.service.prometheus.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "secure-api-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus 